version: '3.7'

networks:
    network:
        driver: bridge

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - network
        depends_on:
            - db
            - nginx

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - "8005:80"
            - "8006:443"
        networks:
            - network
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

    db:
        image: mysql:latest
        env_file:
            - .env
        ports:
            - "33060:3306"
        networks:
            - network
        volumes:
            - ./databaseFiles:/docker-entrypoint-initdb.d

